# Change these first
owner: upal212 # GitHub username
repo: status # GitHub repository name
sites: # List of endpoints to track
  - name: CloudLinkd.com
    url: $CLOUDLINKD
    method: GET
    maxResponseTime: 1000
    
  - name: CloudLinkd Lab
    url: $LAB
    method: GET
    maxResponseTime: 1000
    
  - name: Paris, France
    url: $PARIS
    method: GET
    maxResponseTime: 1000
    
  - name: Amsterdam, Netherlands
    url: $AMSTERDAM
    method: GET
    maxResponseTime: 1000
    
  - name: Frankfurt, Germany
    url: $FRANKFURT
    method: GET
    maxResponseTime: 1000
    
  - name: London, United Kingdom
    url: $LONDON
    method: GET
    maxResponseTime: 1000
    
  - name: Madrid, Spain
    url: $MADRID
    method: GET
    maxResponseTime: 1000
    
  - name: Montreal, Canada
    url: $MONTREAL
    method: GET
    maxResponseTime: 1000
    
  - name: Singapore
    url: $SINGAPORE
    method: GET
    maxResponseTime: 1000
    
  - name: Hyderabad, India
    url: $HYDERABAD
    method: GET
    maxResponseTime: 1000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://www.cloudlinkd.com/wp-content/uploads/2020/03/cloudlinkd-logo-black.png
  name: CloudLinkd Status
  theme: light
  #introTitle: **CloudLinkd Status**
  #introMessage: cloudlinkd.com
  #navbar:
    #- title: CloudLinkd Status
      #href: /
  favicon: https://www.cloudlinkd.com/wp-content/uploads/2019/01/favicon-96.png
  css:   "
   :root {
  --down-border-left-color: #eb3b5a;
  --down-background-color: #eb3b5a;
  --degraded-border-left-color: #f7b731;
  --up-border-left-color: #20bf6b;
}
        "


workflowSchedule:
  responseTime: "*/10 * * * *"
  staticSite: "*/10 * * * *"
  summary: "*/10 * * * *"
  updates: "*/10 * * * *"
  uptime: "*/10 * * * *"

i18n:
  footer: Made with ❤️ by [CloudLinkd](https://www.cloudlinkd.com)
