owner: upal212 # GitHub username
repo: status # GitHub repository name

sites: # List of endpoints to track
  - name: CloudLinkd.com
    url: $CLOUDLINKD
  - name: CloudLinkd Lab
    url: $LAB
  - name: Paris, France
    url: $PARIS
  - name: Amsterdam, Netherlands
    url: $AMSTERDAM
  - name: Frankfurt, Germany
    url: $FRANKFURT
  - name: London, United Kingdom
    url: $LONDON
  - name: Montreal, Canada
    url: $MONTREAL
  - name: Singapore
    url: $SINGAPORE
  - name: Hyderabad, India
    url: $HYDERABAD

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://www.cloudlinkd.com/wp-content/uploads/2022/07/cloudlinkd-logo-black.png
  name: CloudLinkd Status
  theme: light
  #introTitle: **CloudLinkd Status**
  #introMessage: cloudlinkd.com
  #navbar:
    #- title: CloudLinkd Status
      #href: /
  favicon: https://www.cloudlinkd.com/wp-content/uploads/2019/01/favicon-96.png


workflowSchedule:
  responseTime: "*/10 * * * *"
  staticSite: "*/10 * * * *"
  summary: "*/10 * * * *"
  updates: "*/10 * * * *"
  uptime: "*/10 * * * *"

i18n:
  footer: Made with ❤️ by [CloudLinkd](https://www.cloudlinkd.com)
