# Change these first
owner: upal212 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: CloudLinkd.com
    url: $CLOUDLINKD
  - name: CloudLinkd Lab
    url: $CLOUDLINKDLAB
  - name: Frankfurt, Germany
    url: $FRANKFURT
  - name: Madrid, Spain
    url: $MADRID

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://www.cloudlinkd.com/wp-content/uploads/2020/03/cloudlinkd-logo-black.png
  name: CloudLinkd Status
  theme: light
  introTitle: "**CloudLinkd Status**"
  introMessage: cloudlinkd.com
  #navbar:
    #- title: CloudLinkd Status
      #href: /
      
name: Setup CI
on:
  schedule:
    - cron: "*/5 * * * *"
  repository_dispatch:
    types: [setup]
  workflow_dispatch:
jobs:
  release:
    name: Setup Upptime
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - name: Update template
        uses: upptime/uptime-monitor@v1.26.4
        with:
          command: "update-template"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Update response time
        uses: upptime/uptime-monitor@v1.26.4
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: Update summary in README
        uses: upptime/uptime-monitor@v1.26.4
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Generate graphs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Graphs CI
          token: ${{ secrets.GH_PAT }}
      - name: Generate site
        uses: upptime/uptime-monitor@v1.26.4
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - uses: peaceiris/actions-gh-pages@v3.7.3
        name: GitHub Pages Deploy
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: "site/status-page/__sapper__/export/"
          user_name: "Upptime Bot"
          user_email: "73812536+upptime-bot@users.noreply.github.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
